-- CreateEnum
CREATE TYPE "UserType" AS ENUM ('Learner', 'Instructor');

-- CreateEnum
CREATE TYPE "ExternalContentType" AS ENUM ('pdf', 'video', 'youtube_video', 'url', 'image', 'document');

-- CreateEnum
CREATE TYPE "QuestionItemType" AS ENUM ('FillInTheBlanks', 'SingleChoiceQuestion', 'MultiChoiceQuestion', 'FillWholeSentence');

-- CreateEnum
CREATE TYPE "ChoiceAnswerOptions" AS ENUM ('a', 'b', 'c', 'd');

-- CreateTable
CREATE TABLE "User" (
                        "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                        "user_id" STRING NOT NULL,
                        "name" STRING NOT NULL,
                        "user_type" "UserType" NOT NULL,
                        "email_id" STRING NOT NULL,
                        "phone" STRING NOT NULL,
                        "past_experiences" STRING,

                        CONSTRAINT "User_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Conversation" (
                                "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                "title" STRING NOT NULL,

                                CONSTRAINT "Conversation_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "ConversationToUserMapping" (
                                             "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                             "conversation_id" INT4 NOT NULL,
                                             "user_id" STRING NOT NULL,
                                             "send_permission" BOOL NOT NULL,
                                             "receive_permission" BOOL NOT NULL,

                                             CONSTRAINT "ConversationToUserMapping_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "ConversationChat" (
                                    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                    "conversation_id" INT4 NOT NULL,
                                    "content" STRING NOT NULL,
                                    "user_id" STRING NOT NULL,
                                    "timestamp" TIMESTAMP(3) NOT NULL,
                                    "image_url" STRING,
                                    "document_s3_url" STRING,
                                    "video_s3_url" STRING,

                                    CONSTRAINT "ConversationChat_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Course" (
                          "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                          "language" STRING NOT NULL,
                          "title" STRING NOT NULL,
                          "content" STRING NOT NULL,
                          "one_time_price" INT4,
                          "monthly_price" INT4,
                          "one_time_price_premium" INT4,
                          "monthly_price_premium" INT4,
                          "demo_content" STRING,
                          "testimonials" STRING,
                          "total_marks" INT4 NOT NULL,

                          CONSTRAINT "Course_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "CourseToInstructorMapping" (
                                             "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                             "user_id" STRING NOT NULL,

                                             CONSTRAINT "CourseToInstructorMapping_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "CourseToLearnerMapping" (
                                          "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                          "user_id" STRING NOT NULL,
                                          "course_graded_marks" INT4 NOT NULL,

                                          CONSTRAINT "CourseToLearnerMapping_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Lesson" (
                          "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                          "by_id" STRING NOT NULL,
                          "course_id" INT4 NOT NULL,

                          CONSTRAINT "Lesson_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Page" (
                        "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                        "content" STRING NOT NULL,
                        "lesson_id" INT4 NOT NULL,
                        "page_no" INT4 NOT NULL,

                        CONSTRAINT "Page_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "ExternalContentItem" (
                                       "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                       "title" STRING NOT NULL,
                                       "s3_url" STRING NOT NULL,
                                       "by" STRING NOT NULL,
                                       "user_id" STRING NOT NULL,
                                       "page_id" INT4 NOT NULL,

                                       CONSTRAINT "ExternalContentItem_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "QuestionItem" (
                                "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                "title" STRING NOT NULL,
                                "type" "QuestionItemType" NOT NULL,
                                "item_id" INT4 NOT NULL,
                                "page_id" INT4,
                                "assignment_id" INT4,
                                "total_score" INT4 NOT NULL,

                                CONSTRAINT "QuestionItem_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "QuestionItemScore" (
                                     "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                     "remarks" STRING,
                                     "score" INT4 NOT NULL DEFAULT -1,
                                     "percentage" INT4 NOT NULL,
                                     "question_item_id" INT4 NOT NULL,

                                     CONSTRAINT "QuestionItemScore_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "FillInTheBlanksQuestion" (
                                           "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                           "question" STRING NOT NULL,

                                           CONSTRAINT "FillInTheBlanksQuestion_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "FillInTheBlanksAnswer" (
                                         "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                         "possible_answer" STRING NOT NULL,
                                         "question_id" INT4 NOT NULL,

                                         CONSTRAINT "FillInTheBlanksAnswer_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "SingleChoiceQuestion" (
                                        "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                        "question" STRING NOT NULL,
                                        "correct_answer" "ChoiceAnswerOptions" NOT NULL,

                                        CONSTRAINT "SingleChoiceQuestion_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "SingleChoiceAnswer" (
                                      "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                      "question_id" INT4 NOT NULL,
                                      "answer_string" STRING NOT NULL,
                                      "option" "ChoiceAnswerOptions" NOT NULL,

                                      CONSTRAINT "SingleChoiceAnswer_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "MultiChoiceQuestion" (
                                       "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                       "question" STRING NOT NULL,

                                       CONSTRAINT "MultiChoiceQuestion_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "MultiChoiceAnswer" (
                                     "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                     "question_id" INT4 NOT NULL,
                                     "answer_string" STRING NOT NULL,
                                     "is_correct" BOOL NOT NULL,
                                     "option" "ChoiceAnswerOptions" NOT NULL,

                                     CONSTRAINT "MultiChoiceAnswer_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "FillWholeSentenceQuestion" (
                                             "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                             "question_string" STRING NOT NULL,

                                             CONSTRAINT "FillWholeSentenceQuestion_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "FillWholeSentenceSolution" (
                                             "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                             "answer_string" STRING NOT NULL,
                                             "question_id" INT4 NOT NULL,

                                             CONSTRAINT "FillWholeSentenceSolution_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Assignment" (
                              "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                              "title" STRING NOT NULL,
                              "total_marks" INT4 NOT NULL,
                              "course_id" INT4 NOT NULL,

                              CONSTRAINT "Assignment_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "AssignmentToQuestionMapping" (
                                               "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                               "question_id" INT4 NOT NULL,

                                               CONSTRAINT "AssignmentToQuestionMapping_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "FlashCardGroup" (
                                  "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                  "title" STRING NOT NULL,

                                  CONSTRAINT "FlashCardGroup_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "FlashCard" (
                             "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                             "front_side" STRING NOT NULL,
                             "back_side" STRING NOT NULL,
                             "question_audio_url" STRING,
                             "answer_audio_url" STRING,
                             "question_image_url" STRING,
                             "answer_image_url" STRING,
                             "flashcardgroup_id" INT4 NOT NULL,

                             CONSTRAINT "FlashCard_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "UserFlashCardGroup" (
                                      "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                      "flashcardgroup_id" INT4 NOT NULL,
                                      "graduating_interval" INT4 NOT NULL,
                                      "easy_interval" INT4 NOT NULL,
                                      "new_cards_per_day" INT4 NOT NULL,
                                      "max_reviews_per_day" INT4 NOT NULL,
                                      "learning_steps" INT8 NOT NULL,

                                      CONSTRAINT "UserFlashCardGroup_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "UserFlashCard" (
                                 "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                 "userflashcardgroup_id" INT4 NOT NULL,
                                 "flashcard_id" INT4 NOT NULL,
                                 "modified_front_side" STRING NOT NULL,
                                 "modified_back_side" STRING NOT NULL,
                                 "modified_question_audio_url" STRING,
                                 "modified_answer_audio_url" STRING,
                                 "modified_question_image_url" STRING,
                                 "modified_answer_image_url" STRING,
                                 "review_factor" INT4 NOT NULL,
                                 "review_interval" INT4 NOT NULL,

                                 CONSTRAINT "UserFlashCard_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "LiveClass" (
                             "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                             "title" STRING NOT NULL,
                             "start_time" TIMESTAMP(3) NOT NULL,
                             "end_time" TIMESTAMP(3) NOT NULL,

                             CONSTRAINT "LiveClass_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "LiveClassToInstructorMapping" (
                                                "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                                "live_class_id" INT4 NOT NULL,
                                                "user_id" STRING NOT NULL,

                                                CONSTRAINT "LiveClassToInstructorMapping_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "LiveClassToLearnersMapping" (
                                              "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                              "live_class_id" INT4 NOT NULL,
                                              "user_id" STRING NOT NULL,

                                              CONSTRAINT "LiveClassToLearnersMapping_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "LiveChat" (
                            "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                            "live_class_id" INT4 NOT NULL,
                            "by_user_id" STRING NOT NULL,
                            "text" STRING NOT NULL,
                            "diff_time" INT4 NOT NULL,

                            CONSTRAINT "LiveChat_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "WhiteboardEvent" (
                                   "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                   "diff_time" INT4 NOT NULL,
                                   "diff_content" STRING NOT NULL,
                                   "liveclass_id" INT4 NOT NULL,

                                   CONSTRAINT "WhiteboardEvent_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "WhiteboardSlide" (
                                   "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                                   "slide_no" INT4 NOT NULL,
                                   "liveclass_id" INT4 NOT NULL,

                                   CONSTRAINT "WhiteboardSlide_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "User_user_id_key" ON "User"("user_id");

-- CreateIndex
CREATE UNIQUE INDEX "User_email_id_key" ON "User"("email_id");

-- CreateIndex
CREATE UNIQUE INDEX "User_phone_key" ON "User"("phone");

-- CreateIndex
CREATE INDEX "User_user_id_idx" ON "User"("user_id");

-- CreateIndex
CREATE INDEX "User_email_id_idx" ON "User"("email_id");

-- CreateIndex
CREATE INDEX "User_phone_idx" ON "User"("phone");

-- CreateIndex
CREATE INDEX "ConversationToUserMapping_conversation_id_idx" ON "ConversationToUserMapping"("conversation_id");

-- CreateIndex
CREATE INDEX "ConversationToUserMapping_user_id_idx" ON "ConversationToUserMapping"("user_id");

-- CreateIndex
CREATE INDEX "ConversationToUserMapping_conversation_id_user_id_idx" ON "ConversationToUserMapping"("conversation_id", "user_id");

-- CreateIndex
CREATE INDEX "ConversationChat_conversation_id_idx" ON "ConversationChat"("conversation_id");

-- CreateIndex
CREATE INDEX "ConversationChat_user_id_idx" ON "ConversationChat"("user_id");

-- CreateIndex
CREATE INDEX "ConversationChat_conversation_id_user_id_idx" ON "ConversationChat"("conversation_id", "user_id");

-- CreateIndex
CREATE INDEX "Course_one_time_price_premium_idx" ON "Course"("one_time_price_premium");

-- CreateIndex
CREATE INDEX "Course_one_time_price_idx" ON "Course"("one_time_price");

-- CreateIndex
CREATE INDEX "Course_monthly_price_idx" ON "Course"("monthly_price");

-- CreateIndex
CREATE INDEX "Course_monthly_price_premium_idx" ON "Course"("monthly_price_premium");

-- CreateIndex
CREATE INDEX "CourseToInstructorMapping_user_id_idx" ON "CourseToInstructorMapping"("user_id");

-- CreateIndex
CREATE INDEX "CourseToLearnerMapping_user_id_idx" ON "CourseToLearnerMapping"("user_id");

-- CreateIndex
CREATE INDEX "CourseToLearnerMapping_course_graded_marks_idx" ON "CourseToLearnerMapping"("course_graded_marks");

-- CreateIndex
CREATE INDEX "Lesson_by_id_idx" ON "Lesson"("by_id");

-- CreateIndex
CREATE INDEX "Lesson_course_id_idx" ON "Lesson"("course_id");

-- CreateIndex
CREATE INDEX "Lesson_course_id_by_id_idx" ON "Lesson"("course_id", "by_id");

-- CreateIndex
CREATE INDEX "Page_page_no_idx" ON "Page"("page_no");

-- CreateIndex
CREATE INDEX "Page_lesson_id_idx" ON "Page"("lesson_id");

-- CreateIndex
CREATE INDEX "ExternalContentItem_user_id_idx" ON "ExternalContentItem"("user_id");

-- CreateIndex
CREATE INDEX "ExternalContentItem_page_id_idx" ON "ExternalContentItem"("page_id");

-- CreateIndex
CREATE INDEX "QuestionItem_page_id_idx" ON "QuestionItem"("page_id");

-- CreateIndex
CREATE INDEX "QuestionItem_item_id_idx" ON "QuestionItem"("item_id");

-- CreateIndex
CREATE INDEX "QuestionItem_total_score_idx" ON "QuestionItem"("total_score");

-- CreateIndex
CREATE INDEX "QuestionItemScore_question_item_id_idx" ON "QuestionItemScore"("question_item_id");

-- CreateIndex
CREATE INDEX "FillInTheBlanksAnswer_question_id_idx" ON "FillInTheBlanksAnswer"("question_id");

-- CreateIndex
CREATE INDEX "SingleChoiceAnswer_question_id_idx" ON "SingleChoiceAnswer"("question_id");

-- CreateIndex
CREATE INDEX "MultiChoiceAnswer_question_id_idx" ON "MultiChoiceAnswer"("question_id");

-- CreateIndex
CREATE INDEX "FillWholeSentenceSolution_question_id_idx" ON "FillWholeSentenceSolution"("question_id");

-- CreateIndex
CREATE INDEX "Assignment_course_id_idx" ON "Assignment"("course_id");

-- CreateIndex
CREATE INDEX "Assignment_total_marks_idx" ON "Assignment"("total_marks");

-- CreateIndex
CREATE INDEX "AssignmentToQuestionMapping_question_id_idx" ON "AssignmentToQuestionMapping"("question_id");

-- CreateIndex
CREATE INDEX "UserFlashCardGroup_flashcardgroup_id_idx" ON "UserFlashCardGroup"("flashcardgroup_id");

-- CreateIndex
CREATE INDEX "UserFlashCard_flashcard_id_idx" ON "UserFlashCard"("flashcard_id");

-- CreateIndex
CREATE INDEX "UserFlashCard_userflashcardgroup_id_idx" ON "UserFlashCard"("userflashcardgroup_id");

-- CreateIndex
CREATE INDEX "LiveClass_start_time_idx" ON "LiveClass"("start_time");

-- CreateIndex
CREATE INDEX "LiveClassToInstructorMapping_user_id_idx" ON "LiveClassToInstructorMapping"("user_id");

-- CreateIndex
CREATE INDEX "LiveClassToInstructorMapping_live_class_id_idx" ON "LiveClassToInstructorMapping"("live_class_id");

-- CreateIndex
CREATE INDEX "LiveClassToInstructorMapping_live_class_id_user_id_idx" ON "LiveClassToInstructorMapping"("live_class_id", "user_id");

-- CreateIndex
CREATE INDEX "LiveClassToLearnersMapping_user_id_idx" ON "LiveClassToLearnersMapping"("user_id");

-- CreateIndex
CREATE INDEX "LiveClassToLearnersMapping_live_class_id_idx" ON "LiveClassToLearnersMapping"("live_class_id");

-- CreateIndex
CREATE INDEX "LiveClassToLearnersMapping_live_class_id_user_id_idx" ON "LiveClassToLearnersMapping"("live_class_id", "user_id");

-- CreateIndex
CREATE INDEX "LiveChat_live_class_id_id_idx" ON "LiveChat"("live_class_id", "id");

-- CreateIndex
CREATE INDEX "LiveChat_live_class_id_idx" ON "LiveChat"("live_class_id");

-- CreateIndex
CREATE INDEX "LiveChat_by_user_id_idx" ON "LiveChat"("by_user_id");

-- CreateIndex
CREATE INDEX "WhiteboardEvent_liveclass_id_idx" ON "WhiteboardEvent"("liveclass_id");

-- CreateIndex
CREATE INDEX "WhiteboardSlide_slide_no_idx" ON "WhiteboardSlide"("slide_no");

-- CreateIndex
CREATE INDEX "WhiteboardSlide_liveclass_id_idx" ON "WhiteboardSlide"("liveclass_id");

-- CreateIndex
CREATE INDEX "WhiteboardSlide_slide_no_liveclass_id_idx" ON "WhiteboardSlide"("slide_no", "liveclass_id");

-- AddForeignKey
ALTER TABLE "ConversationToUserMapping" ADD CONSTRAINT "ConversationToUserMapping_conversation_id_fkey" FOREIGN KEY ("conversation_id") REFERENCES "Conversation"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ConversationToUserMapping" ADD CONSTRAINT "ConversationToUserMapping_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "User"("user_id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ConversationChat" ADD CONSTRAINT "ConversationChat_conversation_id_fkey" FOREIGN KEY ("conversation_id") REFERENCES "Conversation"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ConversationChat" ADD CONSTRAINT "ConversationChat_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "User"("user_id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "CourseToInstructorMapping" ADD CONSTRAINT "CourseToInstructorMapping_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "User"("user_id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "CourseToLearnerMapping" ADD CONSTRAINT "CourseToLearnerMapping_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "User"("user_id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Lesson" ADD CONSTRAINT "Lesson_by_id_fkey" FOREIGN KEY ("by_id") REFERENCES "User"("user_id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Lesson" ADD CONSTRAINT "Lesson_course_id_fkey" FOREIGN KEY ("course_id") REFERENCES "Course"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Page" ADD CONSTRAINT "Page_lesson_id_fkey" FOREIGN KEY ("lesson_id") REFERENCES "Lesson"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ExternalContentItem" ADD CONSTRAINT "ExternalContentItem_page_id_fkey" FOREIGN KEY ("page_id") REFERENCES "Page"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ExternalContentItem" ADD CONSTRAINT "ExternalContentItem_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "User"("user_id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "QuestionItem" ADD CONSTRAINT "QuestionItem_page_id_fkey" FOREIGN KEY ("page_id") REFERENCES "Page"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "QuestionItem" ADD CONSTRAINT "QuestionItem_assignment_id_fkey" FOREIGN KEY ("assignment_id") REFERENCES "AssignmentToQuestionMapping"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "QuestionItemScore" ADD CONSTRAINT "QuestionItemScore_question_item_id_fkey" FOREIGN KEY ("question_item_id") REFERENCES "QuestionItem"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "FillInTheBlanksAnswer" ADD CONSTRAINT "FillInTheBlanksAnswer_question_id_fkey" FOREIGN KEY ("question_id") REFERENCES "FillInTheBlanksQuestion"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "SingleChoiceAnswer" ADD CONSTRAINT "SingleChoiceAnswer_question_id_fkey" FOREIGN KEY ("question_id") REFERENCES "SingleChoiceQuestion"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "MultiChoiceAnswer" ADD CONSTRAINT "MultiChoiceAnswer_question_id_fkey" FOREIGN KEY ("question_id") REFERENCES "MultiChoiceQuestion"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "FillWholeSentenceSolution" ADD CONSTRAINT "FillWholeSentenceSolution_question_id_fkey" FOREIGN KEY ("question_id") REFERENCES "FillWholeSentenceQuestion"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "FlashCard" ADD CONSTRAINT "FlashCard_flashcardgroup_id_fkey" FOREIGN KEY ("flashcardgroup_id") REFERENCES "FlashCardGroup"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "UserFlashCardGroup" ADD CONSTRAINT "UserFlashCardGroup_flashcardgroup_id_fkey" FOREIGN KEY ("flashcardgroup_id") REFERENCES "FlashCardGroup"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "UserFlashCard" ADD CONSTRAINT "UserFlashCard_userflashcardgroup_id_fkey" FOREIGN KEY ("userflashcardgroup_id") REFERENCES "UserFlashCardGroup"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "UserFlashCard" ADD CONSTRAINT "UserFlashCard_flashcard_id_fkey" FOREIGN KEY ("flashcard_id") REFERENCES "FlashCard"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "LiveClassToInstructorMapping" ADD CONSTRAINT "LiveClassToInstructorMapping_live_class_id_fkey" FOREIGN KEY ("live_class_id") REFERENCES "LiveClass"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "LiveClassToInstructorMapping" ADD CONSTRAINT "LiveClassToInstructorMapping_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "User"("user_id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "LiveClassToLearnersMapping" ADD CONSTRAINT "LiveClassToLearnersMapping_live_class_id_fkey" FOREIGN KEY ("live_class_id") REFERENCES "LiveClass"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "LiveClassToLearnersMapping" ADD CONSTRAINT "LiveClassToLearnersMapping_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "User"("user_id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "LiveChat" ADD CONSTRAINT "LiveChat_live_class_id_fkey" FOREIGN KEY ("live_class_id") REFERENCES "LiveClass"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "WhiteboardEvent" ADD CONSTRAINT "WhiteboardEvent_liveclass_id_fkey" FOREIGN KEY ("liveclass_id") REFERENCES "LiveClass"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "WhiteboardSlide" ADD CONSTRAINT "WhiteboardSlide_liveclass_id_fkey" FOREIGN KEY ("liveclass_id") REFERENCES "LiveClass"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
